### PR TITLE
OPENEUROPA-2047: Add class for timeline to limit width.

### PR DESCRIPTION
**Pull request by nagyad**
image

### CODE REVIEW

**Review by ademarco — APPROVED** [review]
We are wrapping everything around `ecl-editor` class as both title and long text field should be affected by that. This is not ideal but it will do the job, also considering that the ECL2 upgrade is coming soon.

**Comment by voidtek** [comment]
The way to handle it is to add a `<p class='ecl-paragraph'>` for every item.

as we can see in the demo: 
```
<div class="ecl-timeline__body">
        <p class="ecl-paragraph">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec tellus congue, pretium nibh eu, mattis ligula. Integer tempus varius enim ut scelerisque. Curabitur rutrum vestibulum elit ac pulvinar.
        </p>
      </div>
```

**Review by ademarco — CHANGES_REQUESTED** [review]
After talking with @brummbar we should not do this in the pattern but in the field template.

**Comment by nagyad** [comment]
@voidtek As Anto wrote, we need all elements to be wrapped, title, and body as well.

**Review by ademarco — APPROVED** [review]

**Review by ademarco — CHANGES_REQUESTED** [review]
Let's put this on the outside field template instead, it should be like `field--....html.twig`.

**Review by ademarco — APPROVED** [review]
After careful consideration we are back to square one. Approved.

**Review by brummbar — APPROVED** [review]

**Pull request merged**
